-- AlterTable
ALTER TABLE `User` ADD COLUMN `authProvider` ENUM('CREDENTIALS', 'GOOGLE') NOT NULL DEFAULT 'CREDENTIALS',
    MODIFY `phone` VARCHAR(191) NULL,
    MODIFY `password` VARCHAR(191) NULL;
